ATTACH TABLE _ UUID 'fd8b90ee-f35d-4053-a269-f5aadd7e5b4e'
(
    `type` String,
    `days_for_shipping_real` String,
    `days_for_shipment_scheduled` String,
    `benefit_per_order` String,
    `sales_per_customer` String,
    `delivery_status` String,
    `late_delivery_risk` String,
    `category_id` String,
    `category_name` String,
    `customer_city` String,
    `customer_country` String,
    `customer_email` String,
    `customer_fname` String,
    `customer_id` String,
    `customer_lname` String,
    `customer_password` String,
    `customer_segment` String,
    `customer_state` String,
    `customer_street` String,
    `customer_zipcode` String,
    `department_id` String,
    `department_name` String,
    `latitude` String,
    `longitude` String,
    `market` String,
    `order_city` String,
    `order_country` String,
    `order_customer_id` String,
    `order_date_dateorders` String,
    `order_id` String,
    `order_item_cardprod_id` String,
    `order_item_discount` String,
    `order_item_discount_rate` String,
    `order_item_id` String,
    `order_item_product_price` String,
    `order_item_profit_ratio` String,
    `order_item_quantity` String,
    `sales` String,
    `order_item_total` String,
    `order_profit_per_order` String,
    `order_region` String,
    `order_state` String,
    `order_status` String,
    `order_zipcode` String,
    `product_card_id` String,
    `product_category_id` String,
    `product_description` String,
    `product_image` String,
    `product_name` String,
    `product_price` String,
    `product_status` String,
    `shipping_date_dateorders` String,
    `shipping_mode` String,
    `kafka_topic` String,
    `kafka_partition` Int32,
    `kafka_offset` Int64,
    `kafka_timestamp` DateTime
)
ENGINE = MergeTree
ORDER BY kafka_offset
SETTINGS index_granularity = 8192
