networks:
  default:
    name: ${NET}
    external: true
services:
  # AKHQ : Kafka topic monitoring tool
  kafka-connect-ui:
    image: tchiotludo/akhq
    container_name: "akhq"
    ports:
      - "8180:8080"
    environment:
      MICRONAUT_SECURITY_ENABLED: "true"
      MICRONAUT_SECURITY_TOKEN_JWT_ENABLED: "true"
      MICRONAUT_SECURITY_TOKEN_JWT_SIGNATURES_SECRET_GENERATOR_SECRET: "my-super-secret"
      MICRONAUT_SECURITY_BASIC_AUTH_USERS_0_USERNAME: "admin"
      MICRONAUT_SECURITY_BASIC_AUTH_USERS_0_PASSWORD: "admin123"
      MICRONAUT_SECURITY_BASIC_AUTH_USERS_0_ROLES_0: "admin"
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            servlet:
              context-path: /
          connections:
            redpanda:
              properties:
                bootstrap.servers: "PLAINTEXT://kafka-kraft:29092"
          security:
            default-group: admin

