ATTACH MATERIALIZED VIEW _ UUID '471fc6fe-1d6f-4914-a1c6-4b818d201e37' TO default.supply_change_data
(
    `Type` String,
    `DaysForShippingReal` UInt32,
    `DaysForShipmentScheduled` UInt32,
    `BenefitPerOrder` Float64,
    `SalesPerCustomer` Float64,
    `DeliveryStatus` String,
    `LateDeliveryRisk` UInt8,
    `CategoryId` UInt32,
    `CategoryName` String,
    `CustomerCity` String,
    `CustomerCountry` String,
    `CustomerEmail` String,
    `CustomerFname` String,
    `CustomerId` UInt32,
    `CustomerLname` String,
    `CustomerPassword` String,
    `CustomerSegment` String,
    `CustomerState` String,
    `CustomerStreet` String,
    `CustomerZipcode` String,
    `DepartmentId` UInt32,
    `DepartmentName` String,
    `Latitude` Float64,
    `Longitude` Float64,
    `Market` String,
    `OrderCity` String,
    `OrderCountry` String,
    `OrderCustomerId` UInt32,
    `OrderDate` DateTime,
    `OrderId` UInt32,
    `OrderItemCardprodId` UInt32,
    `OrderItemDiscount` Float64,
    `OrderItemDiscountRate` Float64,
    `OrderItemId` UInt32,
    `OrderItemProductPrice` Float64,
    `OrderItemProfitRatio` Float64,
    `OrderItemQuantity` UInt32,
    `Sales` Float64,
    `OrderItemTotal` Float64,
    `OrderProfitPerOrder` Float64,
    `OrderRegion` String,
    `OrderState` String,
    `OrderStatus` String,
    `OrderZipcode` String,
    `ProductCardId` UInt32,
    `ProductCategoryId` UInt32,
    `ProductDescription` String,
    `ProductImage` String,
    `ProductName` String,
    `ProductPrice` Float64,
    `ProductStatus` UInt32,
    `ShippingDate` DateTime,
    `ShippingMode` String,
    `_timestamp` DateTime,
    `_partition` UInt64,
    `_offset` UInt64
)
AS SELECT
    Type,
    toUInt32(`Days for shipping (real)`) AS DaysForShippingReal,
    toUInt32(`Days for shipment (scheduled)`) AS DaysForShipmentScheduled,
    toFloat64(`Benefit per order`) AS BenefitPerOrder,
    toFloat64(`Sales per customer`) AS SalesPerCustomer,
    `Delivery Status` AS DeliveryStatus,
    toUInt8(Late_delivery_risk) AS LateDeliveryRisk,
    toUInt32(`Category Id`) AS CategoryId,
    `Category Name` AS CategoryName,
    `Customer City` AS CustomerCity,
    `Customer Country` AS CustomerCountry,
    `Customer Email` AS CustomerEmail,
    `Customer Fname` AS CustomerFname,
    toUInt32(`Customer Id`) AS CustomerId,
    `Customer Lname` AS CustomerLname,
    `Customer Password` AS CustomerPassword,
    `Customer Segment` AS CustomerSegment,
    `Customer State` AS CustomerState,
    `Customer Street` AS CustomerStreet,
    `Customer Zipcode` AS CustomerZipcode,
    toUInt32(`Department Id`) AS DepartmentId,
    `Department Name` AS DepartmentName,
    toFloat64(Latitude) AS Latitude,
    toFloat64(Longitude) AS Longitude,
    Market,
    `Order City` AS OrderCity,
    `Order Country` AS OrderCountry,
    toUInt32(`Order Customer Id`) AS OrderCustomerId,
    parseDateTimeBestEffort(`order date (DateOrders)`) AS OrderDate,
    toUInt32(`Order Id`) AS OrderId,
    toUInt32(`Order Item Cardprod Id`) AS OrderItemCardprodId,
    toFloat64(`Order Item Discount`) AS OrderItemDiscount,
    toFloat64(`Order Item Discount Rate`) AS OrderItemDiscountRate,
    toUInt32(`Order Item Id`) AS OrderItemId,
    toFloat64(`Order Item Product Price`) AS OrderItemProductPrice,
    toFloat64(`Order Item Profit Ratio`) AS OrderItemProfitRatio,
    toUInt32(`Order Item Quantity`) AS OrderItemQuantity,
    toFloat64(Sales) AS Sales,
    toFloat64(`Order Item Total`) AS OrderItemTotal,
    toFloat64(`Order Profit Per Order`) AS OrderProfitPerOrder,
    `Order Region` AS OrderRegion,
    `Order State` AS OrderState,
    `Order Status` AS OrderStatus,
    `Order Zipcode` AS OrderZipcode,
    toUInt32(`Product Card Id`) AS ProductCardId,
    toUInt32(`Product Category Id`) AS ProductCategoryId,
    `Product Description` AS ProductDescription,
    `Product Image` AS ProductImage,
    `Product Name` AS ProductName,
    toFloat64(`Product Price`) AS ProductPrice,
    toUInt32(`Product Status`) AS ProductStatus,
    parseDateTimeBestEffort(`shipping date (DateOrders)`) AS ShippingDate,
    `Shipping Mode` AS ShippingMode,
    now() AS _timestamp,
    _partition,
    _offset
FROM default.supply_change_kafka
