ATTACH TABLE _ UUID '758a31b8-2efb-4e75-96e4-601a911132c2'
(
    `Type` String,
    `Days for shipping (real)` String,
    `Days for shipment (scheduled)` String,
    `Benefit per order` String,
    `Sales per customer` String,
    `Delivery Status` String,
    `Late_delivery_risk` String,
    `Category Id` String,
    `Category Name` String,
    `Customer City` String,
    `Customer Country` String,
    `Customer Email` String,
    `Customer Fname` String,
    `Customer Id` String,
    `Customer Lname` String,
    `Customer Password` String,
    `Customer Segment` String,
    `Customer State` String,
    `Customer Street` String,
    `Customer Zipcode` String,
    `Department Id` String,
    `Department Name` String,
    `Latitude` String,
    `Longitude` String,
    `Market` String,
    `Order City` String,
    `Order Country` String,
    `Order Customer Id` String,
    `order date (DateOrders)` String,
    `Order Id` String,
    `Order Item Cardprod Id` String,
    `Order Item Discount` String,
    `Order Item Discount Rate` String,
    `Order Item Id` String,
    `Order Item Product Price` String,
    `Order Item Profit Ratio` String,
    `Order Item Quantity` String,
    `Sales` String,
    `Order Item Total` String,
    `Order Profit Per Order` String,
    `Order Region` String,
    `Order State` String,
    `Order Status` String,
    `Order Zipcode` String,
    `Product Card Id` String,
    `Product Category Id` String,
    `Product Description` String,
    `Product Image` String,
    `Product Name` String,
    `Product Price` String,
    `Product Status` String,
    `shipping date (DateOrders)` String,
    `Shipping Mode` String
)
ENGINE = Kafka
SETTINGS kafka_broker_list = '192.168.241.136:9092', kafka_topic_list = 'supply_change_stream', kafka_group_name = 'clickhouse_consumer_group', kafka_format = 'JSONEachRow', kafka_num_consumers = 1
