ATTACH TABLE _ UUID '53323860-adcb-430a-bb7e-89be1a438be8'
(
    `Type` String,
    `DaysForShippingReal` UInt32,
    `DaysForShipmentScheduled` UInt32,
    `BenefitPerOrder` Float64,
    `SalesPerCustomer` Float64,
    `DeliveryStatus` String,
    `LateDeliveryRisk` UInt8,
    `CategoryId` UInt32,
    `CategoryName` String,
    `CustomerCity` String,
    `CustomerCountry` String,
    `CustomerEmail` String,
    `CustomerFname` String,
    `CustomerId` UInt32,
    `CustomerLname` String,
    `CustomerPassword` String,
    `CustomerSegment` String,
    `CustomerState` String,
    `CustomerStreet` String,
    `CustomerZipcode` String,
    `DepartmentId` UInt32,
    `DepartmentName` String,
    `Latitude` Float64,
    `Longitude` Float64,
    `Market` String,
    `OrderCity` String,
    `OrderCountry` String,
    `OrderCustomerId` UInt32,
    `OrderDate` DateTime,
    `OrderId` UInt32,
    `OrderItemCardprodId` UInt32,
    `OrderItemDiscount` Float64,
    `OrderItemDiscountRate` Float64,
    `OrderItemId` UInt32,
    `OrderItemProductPrice` Float64,
    `OrderItemProfitRatio` Float64,
    `OrderItemQuantity` UInt32,
    `Sales` Float64,
    `OrderItemTotal` Float64,
    `OrderProfitPerOrder` Float64,
    `OrderRegion` String,
    `OrderState` String,
    `OrderStatus` String,
    `OrderZipcode` String,
    `ProductCardId` UInt32,
    `ProductCategoryId` UInt32,
    `ProductDescription` String,
    `ProductImage` String,
    `ProductName` String,
    `ProductPrice` Float64,
    `ProductStatus` UInt32,
    `ShippingDate` DateTime,
    `ShippingMode` String,
    `_timestamp` DateTime DEFAULT now(),
    `_partition` UInt64,
    `_offset` UInt64
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(OrderDate)
ORDER BY (OrderDate, OrderId)
SETTINGS index_granularity = 8192
