data_pipeline:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      host: clickhouse-server
      port: 8123
      user: etl_user
      schema: etl
      password: etl_password
      secure: false
      verify: false
