ATTACH TABLE _ UUID '88599e56-ead3-46f4-85fa-797e0b30c61a'
(
    `Type` String,
    `days_for_shipping_real` Int32,
    `days_for_shipment_scheduled` Int32,
    `benefit_per_order` Decimal(10, 2),
    `sales_per_customer` Decimal(10, 7),
    `delivery_status` String,
    `late_delivery_risk` Int8,
    `category_id` Int32,
    `category_name` String,
    `customer_city` String,
    `customer_country` String,
    `customer_email` String,
    `customer_fname` String,
    `customer_id` Int32,
    `customer_lname` String,
    `customer_password` String,
    `customer_segment` String,
    `customer_state` String,
    `customer_street` String,
    `customer_zipcode` String,
    `department_id` Int32,
    `department_name` String,
    `latitude` Decimal(10, 7),
    `longitude` Decimal(11, 8),
    `market` String,
    `order_city` String,
    `order_country` String,
    `order_customer_id` Int32,
    `order_date` DateTime,
    `order_id` Int32,
    `order_item_cardprod_id` Int32,
    `order_item_discount` Decimal(10, 8),
    `order_item_discount_rate` Decimal(10, 9),
    `order_item_id` Int32,
    `order_item_product_price` Decimal(10, 2),
    `order_item_profit_ratio` Decimal(10, 9),
    `order_item_quantity` Int32,
    `sales` Decimal(10, 2),
    `order_item_total` Decimal(10, 7),
    `order_profit_per_order` Decimal(10, 2),
    `order_region` String,
    `order_state` String,
    `order_status` String,
    `order_zipcode` String,
    `product_card_id` Int32,
    `product_category_id` Int32,
    `product_description` String,
    `product_image` String,
    `product_name` String,
    `product_price` Decimal(10, 2),
    `product_status` Int8,
    `shipping_date` DateTime,
    `shipping_mode` String
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(order_date)
ORDER BY (order_date, order_id)
SETTINGS index_granularity = 8192
