networks:
  default:
    name: ${NET}
    external: true

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      # Lokasi database di dalam container
      MB_DB_FILE: /metabase-data/metabase.db
    volumes:
      # Simpan data di folder host ./metabase-data
      - ./metabase-data:/metabase-data
    restart: unless-stopped

